### ISSUE TITLE
Add support for opening .bin word2vec files

### ISSUE THREAD

**Issue by GenTxt** [danielwatson6/skip-thoughts#4]
Hello:

I've tested several skip-thoughts repos including the original without issues but unfortunately I'm encountering problems using tf 1.6 - 1.8 which generates "Illegal instruction (core dumped)" Using ubuntu 18.04, python 3.6.5, nvidia gtx 1070, cuda 9.0. Appears to be a tensorflow issue for many.

Doesn't generate above error under tf 1.5. Placed 'GoogleNews-vectors-negative300.bin'  in folder './word2vecModel' but then this error: IsADirectoryError: [Errno 21] Is a directory: './word2vecModel'

Moved model to project folder and changed to:

parser.add_argument('--embeddings_path', type=str, default="GoogleNews-vectors-negative300.bin",

then this error:

  File "/usr/local/lib/python3.6/dist-packages/gensim/utils.py", line 1332, in unpickle
    return _pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: invalid load key, '3'.

I'm new to python. Should some version of this snippet be added to main.py?

from gensim.models import KeyedVectors
model = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True)

Any help is appreciated.

Cheers

**Comment by danielwatson6** [comment]
@GenTxt please see [this issue thread](https://github.com/tensorflow/tensorflow/issues/17411) in the TensorFlow repository. I am familiar with the error, and it happens with TensorFlow versions 1.6 onward. The reason is that the newer version binaries make use of CPU instructions that your CPU doesn't support.

The easiest "solution" is to downgrade to 1.5. The `master` branch is compatible with this version. However, I am currently working in the `gpu` branch adding GPU support and optimizing the input pipeline with the `tf.data` API, where the newer versions are necessary. So an actual solution, as you can read in the thread, is to [install TensorFlow from sources](https://www.tensorflow.org/install/install_sources).

Hope this helps.

**Comment by danielwatson6** [comment]
@GenTxt regarding the error reading the word embeddings:

- You don't need to modify the python code to read a different path for your word2vec files. That's what argparse is for. When running the script, you can do `python main.py --embeddings_path path/to/your/file`
- Currently, `main.py` expects the word vectors to exist as two files; a binary file and a .syn0 file. I haven't added support for opening .bin files yet. I will modify this issue to a feature request.

**Comment by SSUHan** [comment]
@GenTxt 
I solve this problem by : 
```python
from gensim.models import KeyedVectors
w2v_model = KeyedVectors.load_word2vec_format(FLAGS.embeddings_path, binary=True)
```

**Comment by GenTxt** [comment]
Thanks for the update.
